// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUNGOm7HD44BbXPtAD6XdaWwWOiv_dl3k',
    appId: '1:289021382161:web:e0b1098d0fedbae220abb0',
    messagingSenderId: '289021382161',
    projectId: 'temuin-tekber',
    authDomain: 'temuin-tekber.firebaseapp.com',
    storageBucket: 'temuin-tekber.firebasestorage.app',
    measurementId: 'G-8EERHZ4557',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCifu98bY84-wCfGTbzLga_7Rq8NuO4tkw',
    appId: '1:289021382161:android:5cea9455993c5f5a20abb0',
    messagingSenderId: '289021382161',
    projectId: 'temuin-tekber',
    storageBucket: 'temuin-tekber.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDP0TNLOOVS48IQsMO_E6CXO8eVU9skcY',
    appId: '1:289021382161:ios:bac2208beb9bf2fc20abb0',
    messagingSenderId: '289021382161',
    projectId: 'temuin-tekber',
    storageBucket: 'temuin-tekber.firebasestorage.app',
    iosBundleId: 'com.daniPermana.temuin',
  );

}